site_name: Helixeus-IT Docs

nav:
  - Home: index.md
  - Homelab lessons:
    - Proxmox: proxmox.md
    - Docker: docker.md
    - Configuring SSH: ssh-config.md
    - Resources: resources.md
  - Docker containers:
    - Portainer: portainer.md
    - Speedtest Tracker: speedtest-tracker.md
    - Uptime Kuma: uptime-kuma.md
    - Gotify: gotify.md
    - Nginx Proxy Manager: npm.md
    - Fenrus: fenrus.md
    - Firefly III: firefly3.md
    - Wallos: wallos.md
    - Beszel: beszel.md
    - MkDocs: mkdocs.md
    - Obsidian: obsidian.md
    - Syncthing: syncthing.md
    - Watchtower: watchtower.md
    - FreshRSS: freshrss.md
    - Homepage: homepage.md
  - Other deploys:
    - Snipe-IT: snipe-it.md
    - Ollama+Open-WebUI: ollama-openwebgui.md
    - Pi-Hole: pihole.md
  #  - Jenkins: jenkins.md

theme:
   name: 'material'
   favicon: assets/images/helixeus.png
   logo: assets/images/logo.png
   features:
    - content.code.copy
   palette:
    # Palette toggle for automatic mode     
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences